[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
gl = "0.14.0"
glfw = "0.43.0"
winit = "0.26.1"
cgmath = "0.16.1"
voxel_chunk = "*"
alto = "*"