[package]
name = "crafter"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# I'm documenting this as I translate it from LWJGL and Java.
# It's easier for me.
[dependencies]

rand = "*"
perlin2d = "0.2.6"

gl = "0.14.0" # openGL bindings
glfw = "0.43.0" # GLFW
glam = "0.20.2" # JOML
alto = "*" # openAL wrapper

image = "0.24.1"

# lua jit
mlua = { version = "0.7", features = ["luajit", "vendored"] }